# These are supported funding model platforms

open_collective: yiier
custom: ['https://blog-1251237404.cos.ap-guangzhou.myqcloud.com/20190424153510.png', 'https://blog-1251237404.cos.ap-guangzhou.myqcloud.com/20190424153431.png']
